'''This module contains two dictionaries: `map_geez2ethiop` and `map_ethiop2ipa`.
`map_geez2ethiop` maps Geez characters to their corresponding Ethiopic representation.
`map_ethiop2ipa` maps Ethiopic characters to their corresponding IPA representation.

Example usage:
    # Convert Geez character to Ethiopic representation
    geez_char = 'ሀ'
    ethiop_char = map_geez2ethiop[geez_char]
    print(ethiop_char)  # Output: 'ha'

    # Convert Ethiopic character to IPA representation
    ethiop_char = 'h'
    ipa_char = map_ethiop2ipa[ethiop_char]
    print(ipa_char)  # Output: 'h'
'''

map_geez2ethiop = {
    'ሀ' : 'ha', 
    'ሁ' : 'hu', 
    'ሂ' : 'hi', 
    'ሃ' : 'hA', 
    'ሄ' : 'hE', 
    'ህ' : 'he', 
    'ሆ' : 'ho',

    'ለ' : 'la', 
    'ሉ' : 'lu', 
    'ሊ' : 'li', 
    'ላ' : 'lA', 
    'ሌ' : 'lE', 
    'ል' : 'le', 
    'ሎ' : 'lo', 
    'ሏ' : 'luA',

    'ሐ' : '.ha', 
    'ሑ' : '.hu', 
    'ሒ' : '.hi', 
    'ሓ' : '.hA', 
    'ሔ' : '.hE', 
    'ሕ' : '.he', 
    'ሖ' : '.ho', 
    'ሗ' : '.huA',

    'መ' : 'ma', 
    'ሙ' : 'mu', 
    'ሚ' : 'mi', 
    'ማ' : 'mA', 
    'ሜ' : 'mE', 
    'ም' : 'me', 
    'ሞ' : 'mo', 
    'ሟ' : 'muA', 

    'ሠ' : '\'sa', 
    'ሡ' : '\'su', 
    'ሢ' : '\'si', 
    'ሣ' : '\'sA', 
    'ሤ' : '\'sE', 
    'ሥ' : '\'se', 
    'ሦ' : '\'so', 
    'ሧ' : '\'suA',

    'ረ' : 'ra', 
    'ሩ' : 'ru', 
    'ሪ' : 'ri', 
    'ራ' : 'rA', 
    'ሬ' : 'rE', 
    'ር' : 're', 
    'ሮ' : 'ro', 
    'ሯ' : 'ruA',

    'ሰ' : 'sa', 
    'ሱ' : 'su', 
    'ሲ' : 'si', 
    'ሳ' : 'sA', 
    'ሴ' : 'sE', 
    'ስ' : 'se', 
    'ሶ' : 'so', 
    'ሷ' : 'suA',

    'ሸ' : '^sa', 
    'ሹ' : '^su', 
    'ሺ' : '^si', 
    'ሻ' : '^sA', 
    'ሼ' : '^sE', 
    'ሽ' : '^se', 
    'ሾ' : '^so', 
    'ሿ' : '^suA',

    'ቀ' : 'qa', 
    'ቁ' : 'qu', 
    'ቂ' : 'qi', 
    'ቃ' : 'qA', 
    'ቄ' : 'qE', 
    'ቅ' : 'qe', 
    'ቆ' : 'qo', 
    'ቋ' : 'quA',

    'ቐ' : '.qa', 
    'ቑ' : '.qu', 
    'ቒ' : '.qi', 
    'ቓ' : '.qA', 
    'ቔ' : '.qE', 
    'ቕ' : '.qe', 
    'ቖ' : '.qo',

    'በ' : 'ba', 
    'ቡ' : 'bu', 
    'ቢ' : 'bi', 
    'ባ' : 'bA', 
    'ቤ' : 'bE', 
    'ብ' : 'be', 
    'ቦ' : 'bo', 
    'ቧ' : 'buA',

    'ቨ' : 'va', 
    'ቩ' : 'vu', 
    'ቪ' : 'vi', 
    'ቫ' : 'vA', 
    'ቬ' : 'vE', 
    'ቭ' : 've', 
    'ቮ' : 'vo', 
    'ቯ' : 'vuA',

    'ተ' : 'ta', 
    'ቱ' : 'tu', 
    'ቲ' : 'ti', 
    'ታ' : 'tA', 
    'ቴ' : 'tE', 
    'ት' : 'te', 
    'ቶ' : 'to', 
    'ቷ' : 'tuA',

    'ቸ' : '^ca', 
    'ቹ' : '^cu', 
    'ቺ' : '^ci', 
    'ቻ' : '^cA', 
    'ቼ' : '^cE', 
    'ች' : '^ce', 
    'ቾ' : '^co', 
    'ቿ' : '^cuA',

    'ኀ' : '_ha', 
    'ኁ' : '_hu', 
    'ኂ' : '_hi', 
    'ኃ' : '_hA', 
    'ኄ' : '_hE', 
    'ኅ' : '_he', 
    'ኆ' : '_ho', 
    'ኋ' : '_huA',

    'ነ' : 'na', 
    'ኑ' : 'nu', 
    'ኒ' : 'ni', 
    'ና' : 'nA', 
    'ኔ' : 'nE', 
    'ን' : 'ne', 
    'ኖ' : 'no', 
    'ኗ' : 'nuA',

    'ኘ' : '~n', 
    'ኙ' : '~nu', 
    'ኚ' : '~ni', 
    'ኛ' : '~nA', 
    'ኜ' : '~nE', 
    'ኝ' : '~ne', 
    'ኞ' : '~no',
    'ኟ' : '~nuA',

    'አ' : '\'a', 
    'ኡ' : '\'u', 
    'ኢ' : '\'i', 
    'ኣ' : '\'A', 
    'ኤ' : '\'E', 
    'እ' : '\'e', 
    'ኦ' : '\'o', 
    'ኧ' : '\'uA',

    'ከ' : 'ka', 
    'ኩ' : 'ku', 
    'ኪ' : 'ki', 
    'ካ' : 'kA', 
    'ኬ' : 'kE', 
    'ክ' : 'ke', 
    'ኮ' : 'ko', 
    'ኳ' : 'kuA',

    'ኸ' : '_ka', 
    'ኹ' : '_ku', 
    'ኺ' : '_ki', 
    'ኻ' : '_kA', 
    'ኼ' : '_kE', 
    'ኽ' : '_ke', 
    'ኾ' : '_ko',

    'ወ' : 'wa', 
    'ዉ' : 'wu', 
    'ዊ' : 'wi', 
    'ዋ' : 'wA', 
    'ዌ' : 'wE', 
    'ው' : 'we', 
    'ዎ' : 'wo',

    'ዐ' : '`a', 
    'ዑ' : '`u', 
    'ዒ' : '`i', 
    'ዓ' : '`A', 
    'ዔ' : '`E', 
    'ዕ' : '`e', 
    'ዖ' : '`o',

    'ዘ' : 'za', 
    'ዙ' : 'zu', 
    'ዚ' : 'zi', 
    'ዛ' : 'zA', 
    'ዜ' : 'zE', 
    'ዝ' : 'ze', 
    'ዞ' : 'zo', 
    'ዟ' : 'zuA',

    'ዠ' : '^z', 
    'ዡ' : '^zu', 
    'ዢ' : '^zi', 
    'ዣ' : '^zA', 
    'ዤ' : '^zE', 
    'ዥ' : '^ze', 
    'ዦ' : '^zo', 
    'ዧ' : '^zuA',

    'የ' : 'ya', 
    'ዩ' : 'yu', 
    'ዪ' : 'yi', 
    'ያ' : 'yA', 
    'ዬ' : 'yE', 
    'ይ' : 'ye', 
    'ዮ' : 'yo',

    'ደ' : 'da', 
    'ዱ' : 'du', 
    'ዲ' : 'di', 
    'ዳ' : 'dA', 
    'ዴ' : 'dE', 
    'ድ' : 'de', 
    'ዶ' : 'do', 
    'ዷ' : 'duA',

    'ጀ' : '^ga', 
    'ጁ' : '^gu', 
    'ጂ' : '^gi', 
    'ጃ' : '^gA', 
    'ጄ' : '^gE', 
    'ጅ' : '^ge', 
    'ጆ' : '^go', 
    'ጇ' : '^guA',

    'ገ' : 'ga', 
    'ጉ' : 'gu', 
    'ጊ' : 'gi', 
    'ጋ' : 'gA', 
    'ጌ' : 'gE', 
    'ግ' : 'ge', 
    'ጎ' : 'go', 
    'ጓ' : 'guA',

    'ጘ' : '.ga', 
    'ጙ' : '.gu', 
    'ጚ' : '.gi', 
    'ጛ' : '.gA', 
    'ጜ' : '.gE', 
    'ጝ' : '.ge', 
    'ጞ' : '.go',

    'ጠ' : '.ta', 
    'ጡ' : '.tu', 
    'ጢ' : '.ti', 
    'ጣ' : '.tA', 
    'ጤ' : '.tE', 
    'ጥ' : '.te', 
    'ጦ' : '.to', 
    'ጧ' : '.tuA',

    'ጨ' : '^Ca', 
    'ጩ' : '^Cu', 
    'ጪ' : '^Ci', 
    'ጫ' : '^CA', 
    'ጬ' : '^CE', 
    'ጭ' : '^Ce', 
    'ጮ' : '^Co', 
    'ጯ' : '^CuA',

    'ጰ' : '.pa', 
    'ጱ' : '.pu', 
    'ጲ' : '.pi', 
    'ጳ' : '.pA', 
    'ጴ' : '.pE', 
    'ጵ' : '.pe', 
    'ጶ' : '.po',
    'ጷ' : '.puA',

    'ጸ' : '.sa', 
    'ጹ' : '.su', 
    'ጺ' : '.si', 
    'ጻ' : '.sA', 
    'ጼ' : '.sE', 
    'ጽ' : '.se', 
    'ጾ' : '.so', 
    'ጿ' : '.suA',

    'ፀ' : '.ca', 
    'ፁ' : '.cu', 
    'ፂ' : '.ci', 
    'ፃ' : '.cA', 
    'ፄ' : '.cE', 
    'ፅ' : '.ce', 
    'ፆ' : '.co', 
    'ፇ' : '.cuA',

    'ፈ' : 'fa', 
    'ፉ' : 'fu', 
    'ፊ' : 'fi', 
    'ፋ' : 'fA', 
    'ፌ' : 'fE', 
    'ፍ' : 'fe', 
    'ፎ' : 'fo', 
    'ፏ' : 'fuA',

    'ፐ' : 'pa', 
    'ፑ' : 'pu', 
    'ፒ' : 'pi', 
    'ፓ' : 'pA', 
    'ፔ' : 'pE', 
    'ፕ' : 'pe', 
    'ፖ' : 'po', 
    'ፗ' : 'pua',
}

map_ethiop2ipa = {
    'h' : r'h',
    'l' : r'l',
    '.h' : r'\.*h',
    'm' : r'm',
    '\'s' : r'\'s',
    'r' : r'r',
    's' : r's',
    '^s' : r'\v{s}',
    'q' : r'q',
    '.q' : r'\.q',
    'b' : r'b',
    'v' : r'v',
    't' : r't',
    '^c' : r'\v{c}',
    '_h' : r'\=*h',
    'n' : r'n',
    '~n' : r'\~n',
    '\'' : '\'',
    'k' : r'k',
    '_k' : r'\=*k',
    'w' : r'w',
    '`' : r'\textrevapostrophe{}',
    'z' : r'z',
    '^z' : r'\v{z}',
    'y' : r'y',
    'd' : r'd',
    '.d' : r'\.*d',
    '^g' : r'\v{g}',
    'g' : r'g',
    '.g' : r'\.*g',
    '.t' : r'\.*t',
    '^C' : r'\v{\.*c}',
    '.p' : r'\.*p',
    '.s' : r'\.*s',
    '.c' : r'\.*c',
    'f' : r'f',
    'p' : r'p',
    '\'q' : r'\'q',
    '\'k' : r'\'k',
    '\'h' : r'\'h',
    '\'g' : r'\'g',
    'a' : r'\"a',
    'u' : r'u',
    'i' : r'i',
    'A' : r'a',
    'E' : r'e',
    'e' : r'\textschwa{}',
    'o' : r'o',
    'uA' : r'\textsuperscript{w}a',
}